import { OTPInput, OTPInputContext } from 'input-otp';
import * as React from 'react';
import { cn } from '@/lib/utils';
const InputOTP = React.forwardRef(({ className, containerClassName, ...props }, ref) => <OTPInput ref={ref} containerClassName={cn('flex items-center gap-2 has-[:disabled]:opacity-50', containerClassName)} className={cn('disabled:cursor-not-allowed', className)} {...props} />);
InputOTP.displayName = 'InputOTP';
const InputOTPGroup = React.forwardRef(({ className, ...props }, ref) => <div ref={ref} className={cn('flex items-center', className)} {...props} />);
InputOTPGroup.displayName = 'InputOTPGroup';
const InputOTPSlot = React.forwardRef(({ index, className, ...props }, ref) => { const ctx = React.useContext(OTPInputContext); const slot = ctx.slots[index]; return <div ref={ref} className={cn('relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-sm shadow-sm transition-all first:rounded-l-md first:border-l last:rounded-r-md', slot?.isActive && 'z-10 ring-1 ring-ring', className)} {...props}>{slot?.char}</div>; });
InputOTPSlot.displayName = 'InputOTPSlot';
export { InputOTP, InputOTPGroup, InputOTPSlot };
