import * as React from 'react';
import * as SheetPrimitive from '@radix-ui/react-dialog';
import { cn } from '@/lib/utils';
import { X } from 'lucide-react';
const Sheet = SheetPrimitive.Root;
const SheetTrigger = SheetPrimitive.Trigger;
const SheetClose = SheetPrimitive.Close;
const SheetPortal = SheetPrimitive.Portal;
const SheetOverlay = React.forwardRef(({ className, ...props }, ref) => <SheetPrimitive.Overlay className={cn('fixed inset-0 z-50 bg-black/80', className)} {...props} ref={ref} />);
const SheetContent = React.forwardRef(({ className, children, side = 'right', ...props }, ref) => (<SheetPortal><SheetOverlay /><SheetPrimitive.Content ref={ref} className={cn('fixed z-50 gap-4 bg-background p-6 shadow-lg transition', side === 'right' && 'inset-y-0 right-0 h-full w-3/4 border-l sm:max-w-sm', side === 'left' && 'inset-y-0 left-0 h-full w-3/4 border-r sm:max-w-sm', side === 'top' && 'inset-x-0 top-0 border-b', side === 'bottom' && 'inset-x-0 bottom-0 border-t', className)} {...props}>{children}<SheetPrimitive.Close className='absolute right-4 top-4 rounded-sm opacity-70 hover:opacity-100'><X className='h-4 w-4' /></SheetPrimitive.Close></SheetPrimitive.Content></SheetPortal>));
const SheetHeader = ({ className, ...props }) => <div className={cn('flex flex-col space-y-2 text-center sm:text-left', className)} {...props} />;
const SheetTitle = React.forwardRef(({ className, ...props }, ref) => <SheetPrimitive.Title ref={ref} className={cn('text-lg font-semibold text-foreground', className)} {...props} />);
const SheetDescription = React.forwardRef(({ className, ...props }, ref) => <SheetPrimitive.Description ref={ref} className={cn('text-sm text-muted-foreground', className)} {...props} />);
export { Sheet, SheetPortal, SheetOverlay, SheetTrigger, SheetClose, SheetContent, SheetHeader, SheetTitle, SheetDescription };
